name = "PrimeNumberTheoremAnd"
version = "0.1.0"
defaultTargets = ["PrimeNumberTheoremAnd"]

[leanOptions]
pp.unicode.fun = true
pp.proofs.withType = false
autoImplicit = false
relaxedAutoImplicit = false
linter.mathlibStandardSet = true
linter.style.openClassical = false
linter.style.longLine = false
linter.style.emptyLine = false
linter.flexible = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0-rc1"

[[require]]
name = "LeanArchitect"
git = "https://github.com/e-vergo/LeanArchitect.git"
rev = "main"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "main"

[[require]]
name = "doc-gen4"
scope = "leanprover"
rev = "v4.27.0-rc1"

[[lean_lib]]
name = "PrimeNumberTheoremAnd"
